openapi: 3.0.3
info:
  title: FamiliesShare API
  description: FamiliesShare API
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8080/'

paths:
  /group/{groupId}/activityrequests:
    parameters:
      - in: path
        name: groupId
        description: Group ID
        required: true
        schema:
          type: string
    post:
      tags:
        - Activity Requests
      summary: Create new activity request
      operationId: createActivityRequest
      requestBody:
        $ref: '#/components/requestBodies/ActivityRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '409':
          description: User already exists

    get:
      tags:
        - Activity Requests
      summary: Get all activity requests of the authenticated user
      operationId: getActivityRequests
      responses:
        '401':
          description: Unauthorized
        '200':
          description: Array of activity requests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ActivityRequest'

  /group/{groupId}/activityrequests/{activityRequestId}:
    parameters:
      - in: path
        name: groupId
        description: Group ID
        required: true
        schema:
          type: string
      - in: path
        name: activityRequestId
        description: Activity Request ID
        required: true
        schema:
          type: string

    get:
      tags:
        - Activity Requests
      summary: Get activity request by id
      operationId: getActivityRequestById
      responses:
        '401':
          description: Unauthorized
        '200':
          description: The requested activity request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityRequest'

    patch:
      tags:
        - Activity Requests
      summary: Update activity request
      operationId: updateActivityRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivityRequest'
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Activity request not found
        '200':
          description: The updated activity request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityRequest'

    delete:
      tags:
        - Activity Requests
      summary: Delete activity request
      operationId: deleteActivityRequest
      responses:
        '401':
          description: Unauthorized
        '200':
          description: Activity Request Deleted


  /group/{groupId}/activityrequests/{activityRequestId}/compatibleTimeslots:
    parameters:
      - in: path
        name: groupId
        description: Group ID
        required: true
        schema:
          type: string
      - in: path
        name: activityRequestId
        description: Activity Request ID
        required: true
        schema:
          type: string
          

    get:
      tags:
        - Activity Requests
      summary: Get all compatible timeslots of the activity request
      operationId: getCompatibleTimeslots
      responses:
        '401':
          description: Unauthorized
        '404':
          description: Activity request not found
        '200':
          description: Array of compatible timeslots

components:
  schemas:
    ActivityRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        color:
          type: string
        children:
          type: array
          items:
            type: string
          minItems: 1
        date:
          type: string
        startTime:
          type: string
        endTime:
          type: string

  requestBodies:
    ActivityRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActivityRequest'







