openapi: 3.0.3
info:
  title: FamiliesShare API
  description: FamiliesShare API
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8080/'

paths:
  /group/{groupId}/activities/{activityId}/timeslots/{timeslotId}/invites:
    post:
      tags:
        - Invites
      summary: Create a new invite
      operationId: createInvite
      parameters:
        - in: path
          name: groupId
          description: The group id
          required: true
          schema:
            type: string
        - in: path
          name: activityId
          description: The activity id
          required: true
          schema:
            type: string
        - in: path
          name: timeslotId
          description: The timeslot id
          required: true
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invitees:
                  type: array
                items:
                  type: string

      responses:
        '200':
          description: Invite created
        '401':
          description: Unauthorized


  /user/{userId}/invites:
    get:
      tags:
        - Invites
      summary: Get all invites for a user
      operationId: getInvites
      parameters:
        - in: path
          name: userId
          description: The user id
          required: true
          schema:
            type: string

        - in: query
          name: status
          description: The status of the invite
          required: false
          schema:
            type: string
            enum:
              - pending
              - accepted

      responses:
        '200':
          description: Invites found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invite'
        '401':
          description: Unauthorized
        '404':
          description: Not found


  /user/{userId}/invites/{timeslot_id}/accept:
    post:
      tags:
        - Invites
      summary: Accept an invite
      operationId: acceptInvite
      parameters:
        - in: path
          name: userId
          description: The user id
          required: true
          schema:
            type: string

        - in: path
          name: timeslot_id
          description: The timeslot id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invite accepted
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found

  /user/{userId}/invites/{timeslot_id}/decline:
    post:
      tags:
        - Invites
      summary: Decline an invite
      operationId: declineInvite
      parameters:
        - in: path
          name: userId
          description: The user id
          required: true
          schema:
            type: string

        - in: path
          name: timeslot_id
          description: The timeslot id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invite declined
        '401':
          description: Unauthorized

components:
  schemas:
    Invite:
      type: object
      properties:
        timeslot_id:
          type: string

        inviter_id:
          type: string

        invitee_id:
          type: string

        group_id:
          type: string

        activity_id:
          type: string

        status:
          type: string








