# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Decrypt Secrets
      run: gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.GPG_PASSPHRASE }} --output src/google_api_keyfile.json .github/workflows/google_api_keyfile.json.gpg

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Doppler CLI
      uses: DopplerHQ/cli-action@v1

    - name : Install Node.js Dependencies
      run: npm ci

    - name : Run Tests
      run: doppler run npm test
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      continue-on-error: true
